version: "3"
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox-debug
    shm_size: '2gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module1:
    image: nksanoro/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=searchModule.xml
    volumes:
      - ./output/firefox-search-result:/usr/share/udemy/test-output
  search-module2:
    image: nksanoro/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=searchModule.xml
    volumes:
      - ./output/chrome-search-result:/usr/share/udemy/test-output
  book-flight-module1:
    image: nksanoro/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=bookFlightModule.xml
    volumes:
      - ./output/firefox-book-result:/usr/share/udemy/test-output
  book-flight-module2:
    image: nksanoro/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=bookFlightModule.xml
    volumes:
      - ./output/chrome-book-result:/usr/share/udemy/test-output

