version: "3"
services:
  hub:
    image: dosel/zalenium
    ports:
      - "4444:4444"
      - "5555:5555"
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      start --desiredContainers 10
            --maxDockerSeleniumContainers 20
            --maxTestSessions 3 
            --videoRecordingEnabled false
  search-module:
    image: nksanoro/selenium-docker
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=bookFlightModule.xml
    volumes:
      - ./output/search-result:/usr/share/udemy/test-output